--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaDevGuy/BetterInfo
build-by-default: true
branches:
- main
projects:
  BetterInfo:
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
    lints:
      phpstan: false
...
