name: BetterInfo 
author: DaDevGuy,JoeXerus
main: BetterInfo\DaDevGuy\Main
version: 1.0.0
api: 4.0.0

commands: 
 myinfo:
  description: "Show Information About You"
  permission: betterinfo.info.cmd

permissions: 
 betterinfo.info.cmd:
  https://discord.gg/f7Ep2Jj6default: op
